-- MySQL Script generated by MySQL Workbench
-- Tue Dec 24 22:16:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DesafioDIO_Ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DesafioDIO_Ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DesafioDIO_Ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `DesafioDIO_Ecommerce` ;

-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Categoria` (
  `id_Categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_Categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Categoria`),
  UNIQUE INDEX `idCategoria_UNIQUE` (`id_Categoria` ASC) VISIBLE,
  UNIQUE INDEX `nome_Categoria_UNIQUE` (`nome_Categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Conta` (
  `id_Conta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_Conta` VARCHAR(100) NOT NULL,
  `email_Conta` VARCHAR(100) NOT NULL,
  `telefone_Conta` VARCHAR(15) NOT NULL,
  `status_Conta` ENUM('ativo', 'inativo') NOT NULL DEFAULT 'ativo',
  `data_cadastro_Conta` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_Conta`),
  UNIQUE INDEX `idConta_UNIQUE` (`id_Conta` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Endereco` (
  `id_Endereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NULL,
  `complemento` VARCHAR(50) NULL,
  `bairro` VARCHAR(50) NULL,
  `tipo_endereco` ENUM('residencial', 'comercial') NOT NULL,
  `tipo_entidade` ENUM('cliente', 'fornecedor', 'vendedor') NOT NULL,
  `Conta_id_Conta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Endereco`, `Conta_id_Conta`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`id_Endereco` ASC) VISIBLE,
  INDEX `fk_Endereco_Conta1_idx` (`Conta_id_Conta` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `DesafioDIO_Ecommerce`.`Conta` (`id_Conta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Estoque` (
  `id_Estoque` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantidade_estoque` INT NOT NULL,
  `valor_total_estoque` DECIMAL(10,2) NOT NULL,
  `Produto_id_Produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Estoque`, `Produto_id_Produto`),
  UNIQUE INDEX `id_Estoque_UNIQUE` (`id_Estoque` ASC) VISIBLE,
  INDEX `fk_Estoque_Produto1_idx` (`Produto_id_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produto1`
    FOREIGN KEY (`Produto_id_Produto`)
    REFERENCES `DesafioDIO_Ecommerce`.`Produto` (`id_Produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Forma_Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Forma_Pagamento` (
  `id_Forma_Pagamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_Forma_Pagamento` ENUM('cartão', 'boleto', 'PIX') NOT NULL,
  `detalhes_Forma_Pagamento` LONGTEXT NOT NULL COMMENT 'chave PIX, número do cartão',
  `data_cadastro_Forma_Pagamento` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Conta_id_Conta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Forma_Pagamento`, `Conta_id_Conta`),
  UNIQUE INDEX `idForma_Pagamento_UNIQUE` (`id_Forma_Pagamento` ASC) VISIBLE,
  INDEX `fk_Forma_Pagamento_Conta1_idx` (`Conta_id_Conta` ASC) VISIBLE,
  CONSTRAINT `fk_Forma_Pagamento_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `DesafioDIO_Ecommerce`.`Conta` (`id_Conta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Fornecedor` (
  `cnpj_Fornecedor` VARCHAR(18) NOT NULL,
  `Conta_id_Conta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cnpj_Fornecedor`, `Conta_id_Conta`),
  UNIQUE INDEX `cnpj_Fornecedor_UNIQUE` (`cnpj_Fornecedor` ASC) VISIBLE,
  INDEX `fk_Fornecedor_Conta1_idx` (`Conta_id_Conta` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `DesafioDIO_Ecommerce`.`Conta` (`id_Conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Fornecimento_de_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Fornecimento_de_produtos` (
  `Produto_id_Produto` INT UNSIGNED NOT NULL,
  `Fornecedor_cnpj_Fornecedor` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`Produto_id_Produto`, `Fornecedor_cnpj_Fornecedor`),
  INDEX `fk_Fornecimento_de_produtos_Fornecedor1_idx` (`Fornecedor_cnpj_Fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto1`
    FOREIGN KEY (`Produto_id_Produto`)
    REFERENCES `DesafioDIO_Ecommerce`.`Produto` (`id_Produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Fornecimento_de_produtos_Fornecedor1`
    FOREIGN KEY (`Fornecedor_cnpj_Fornecedor`)
    REFERENCES `DesafioDIO_Ecommerce`.`Fornecedor` (`cnpj_Fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Item_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Item_Pedido` (
  `id_Item_Pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantidade_Item_Pedido` INT UNSIGNED NOT NULL,
  `preco_unitario_Item_Pedido` DECIMAL(10,2) NOT NULL,
  `Pedido_id_Pedido` INT UNSIGNED NOT NULL,
  `Produto_id_Produto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Item_Pedido`, `Pedido_id_Pedido`, `Produto_id_Produto`),
  UNIQUE INDEX `id_Item_Pedido_UNIQUE` (`id_Item_Pedido` ASC) VISIBLE,
  INDEX `fk_Item_Pedido_Pedido1_idx` (`Pedido_id_Pedido` ASC) VISIBLE,
  INDEX `fk_Item_Pedido_Produto1_idx` (`Produto_id_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_id_Pedido`)
    REFERENCES `DesafioDIO_Ecommerce`.`Pedido` (`id_Pedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Item_Pedido_Produto1`
    FOREIGN KEY (`Produto_id_Produto`)
    REFERENCES `DesafioDIO_Ecommerce`.`Produto` (`id_Produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Pedido` (
  `id_Pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status_Pedido` ENUM('aberto', 'enviado', 'cancelado', 'concluído') NOT NULL DEFAULT 'aberto',
  `data_Pedido` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_entrega_Pedido` DATETIME NULL,
  `codigo_rastreamento` VARCHAR(50) NULL,
  `Conta_id_Conta` INT UNSIGNED NOT NULL,
  `Endereco_id_Endereco` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Pedido`, `Conta_id_Conta`, `Endereco_id_Endereco`, `status_Pedido`),
  UNIQUE INDEX `id_Pedido_UNIQUE` (`id_Pedido` ASC) VISIBLE,
  INDEX `fk_Pedido_Conta1_idx` (`Conta_id_Conta` ASC) VISIBLE,
  INDEX `fk_Pedido_Endereco1_idx` (`Endereco_id_Endereco` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `DesafioDIO_Ecommerce`.`Conta` (`id_Conta`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pedido_Endereco1`
    FOREIGN KEY (`Endereco_id_Endereco`)
    REFERENCES `DesafioDIO_Ecommerce`.`Endereco` (`id_Endereco`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Pessoa_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Pessoa_Fisica` (
  `cpf` VARCHAR(14) NOT NULL,
  `idade` INT UNSIGNED NULL,
  `Conta_id_Conta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cpf`, `Conta_id_Conta`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_Pessoa_Fisica_Conta1_idx` (`Conta_id_Conta` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Fisica_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `DesafioDIO_Ecommerce`.`Conta` (`id_Conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Pessoa_Juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Pessoa_Juridica` (
  `cnpj` VARCHAR(18) NOT NULL,
  `Conta_id_Conta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cnpj`, `Conta_id_Conta`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  INDEX `fk_Pessoa_Juridica_Conta1_idx` (`Conta_id_Conta` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Juridica_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `DesafioDIO_Ecommerce`.`Conta` (`id_Conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Produto` (
  `id_Produto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_Produto` VARCHAR(100) NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  `descricao_Produto` LONGTEXT NULL,
  `Categoria_id_Categoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Produto`, `Categoria_id_Categoria`),
  INDEX `fk_Produto_Categoria1_idx` (`Categoria_id_Categoria` ASC) VISIBLE,
  UNIQUE INDEX `id_Produto_UNIQUE` (`id_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_id_Categoria`)
    REFERENCES `DesafioDIO_Ecommerce`.`Categoria` (`id_Categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Venda_de_Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Venda_de_Vendedor` (
  `Produto_id_Produto` INT UNSIGNED NOT NULL,
  `Vendedor_id_Vendedor` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Produto_id_Produto`, `Vendedor_id_Vendedor`),
  INDEX `fk_Produto_has_Vendedor_Vendedor1_idx` (`Vendedor_id_Vendedor` ASC) VISIBLE,
  INDEX `fk_Produto_has_Vendedor_Produto1_idx` (`Produto_id_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Vendedor_Produto1`
    FOREIGN KEY (`Produto_id_Produto`)
    REFERENCES `DesafioDIO_Ecommerce`.`Produto` (`id_Produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Produto_has_Vendedor_Vendedor1`
    FOREIGN KEY (`Vendedor_id_Vendedor`)
    REFERENCES `DesafioDIO_Ecommerce`.`Vendedor` (`id_Vendedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DesafioDIO_Ecommerce`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DesafioDIO_Ecommerce`.`Vendedor` (
  `id_Vendedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf_vendedor` VARCHAR(14) NULL,
  `cnpj_vendedor` VARCHAR(18) NULL,
  `Conta_id_Conta` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_Vendedor`, `Conta_id_Conta`),
  UNIQUE INDEX `id_Vendedor_UNIQUE` (`id_Vendedor` ASC) VISIBLE,
  UNIQUE INDEX `cpf_vendedor_UNIQUE` (`cpf_vendedor` ASC) VISIBLE,
  INDEX `fk_Vendedor_Conta1_idx` (`Conta_id_Conta` ASC) VISIBLE,
  CONSTRAINT `fk_Vendedor_Conta1`
    FOREIGN KEY (`Conta_id_Conta`)
    REFERENCES `DesafioDIO_Ecommerce`.`Conta` (`id_Conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
